spring.application.name=api
server.address=0.0.0.0
#Configuration de la base de donnees
spring.datasource.url=jdbc:postgresql://82.66.239.16:5432/soutien-plus
spring.datasource.username=soutien
spring.datasource.password=soutienplus
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-bean-definition-overriding=true

#Configuration de MailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=whatif.seriousgame@gmail.com
spring.mail.password=kfxq pvkh nuvo zbab
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.secret-key="Vt6yo0jsh0AmNDpa2n/2Gtx/z2+NaQTHqJGaGTlpD1TLIy41ZiN+kJshU/fV8fVCUEjHKiVzpiFsgaJEh0cV3w=="
app.expiration-time=108000000

encryption.password=soutienplus38
encryption.salt=7f6c8e4a5b3d2e7a
